# Generated by Django 4.2.3 on 2023-10-22 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('attending', models.BooleanField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.event')),
            ],
        ),
    ]
