# Generated by Django 4.2.3 on 2023-10-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_delete_questionimage_alter_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images'),
        ),
    ]
