# Generated by Django 4.2.3 on 2023-10-31 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_alter_question_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 31, 3, 52, 40, 905228, tzinfo=datetime.timezone.utc)),
        ),
    ]
