# Generated by Django 4.2.6 on 2023-10-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Ela', 'Ela')], max_length=20)),
                ('level', models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Ela', 'Ela')], max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
