# Generated by Django 4.2.3 on 2023-10-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.TextField(default='Blank', max_length=200),
        ),
    ]
