# Generated by Django 4.2.3 on 2023-10-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_alter_message_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
