# Generated by Django 4.2.3 on 2023-10-22 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_eventresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='updated',
        ),
        migrations.AddField(
            model_name='eventresponse',
            name='created',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
