# Generated by Django 4.2.3 on 2023-10-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_response_updated_eventresponse_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventresponse',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
