# Generated by Django 4.2.3 on 2023-10-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_eventresponse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventresponse',
            name='attending',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
