# Generated by Django 4.2.3 on 2023-10-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Ela', 'Ela')], max_length=20),
        ),
    ]
