# Generated by Django 4.2.3 on 2023-10-25 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_alter_questionimage_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionimage',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='questionimg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.questionimage'),
        ),
    ]
