# Generated by Django 4.2.3 on 2023-10-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_remove_questionimage_question_question_questionimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionimg',
            field=models.ImageField(default='default.jpg', upload_to='question_images'),
        ),
    ]
