# Generated by Django 4.2.3 on 2023-10-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_rename_questionimg_question_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionImage',
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to='question_images'),
        ),
    ]
