# Generated by Django 4.2.3 on 2023-10-31 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_alter_question_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 3, 53, 9, 309808, tzinfo=datetime.timezone.utc)),
        ),
    ]
