# Generated by Django 4.2.3 on 2023-10-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='level',
            field=models.CharField(choices=[('Elementary School', 'Elementary'), ('Middle School', 'Middle'), ('High School', 'High'), ('College', 'College')], max_length=20),
        ),
    ]
