# Generated by Django 4.2.6 on 2023-10-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_alter_message_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='level',
            field=models.CharField(choices=[('Elementary', 'Elementary'), ('Middle', 'Middle'), ('High', 'High'), ('College', 'College')], max_length=20),
        ),
    ]
